# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: FIDES API
  description: FIDES web app API
  version: "1.0.0"
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
resourcePath: /Badges
description: Manage the badge
apis:

- path: /badges
  operations:
    - httpMethod: GET
      summary: Get badge
      notes: Fetch all badges
      nickname: badges
      consume:
        - application/json
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token

- path: /badges
  operations:
    - httpMethod: POST
      summary: add badge
      notes: Returns a saved badge
      nickname: badges
      consumes:
        - multipart/form-data
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token
        - name: name
          dataType: string
          paramType: formData
          required: true
          description: category title
        - name: description
          dataType: string
          paramType: formData
          required: true
          description: category description
        - name: narrative
          dataType: string
          paramType: formData
          required: true
          description: narrative
        - name: category
          dataType: string
          paramType: formData
          required: true
          description: category id
        - name: image
          dataType: file
          paramType: formData
          required: true
          description: trustmark file of organization

- path: /badges/{bid}
  operations:
    - httpMethod: PUT
      summary: Update badge
      notes: Returns a updated badge
      nickname: badges
      consumes:
        - multipart/form-data
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token
        - name: bid
          dataType: string
          paramType: formData
          required: true
          description: badge id
        - name: name
          dataType: string
          paramType: formData
          required: true
          description: category title
        - name: description
          dataType: string
          paramType: formData
          required: true
          description: category description
        - name: narrative
          dataType: string
          paramType: formData
          required: true
          description: narrative
        - name: category
          dataType: string
          paramType: formData
          required: true
          description: category id
        - name: image
          dataType: file
          paramType: formData
          required: true
          description: trustmark file of organization

- path: /badges/{bid}
  operations:
    - httpMethod: DELETE
      summary: remove badge
      notes: Returns a deleted badge
      nickname: badges
      consumes:
        - application/json
      parameters:
      - name: Authorization
        dataType: string
        paramType: header
        required: true
        description: authorization token
      - name: bid
        dataType: string
        paramType: path
        required: true
        description: badge unique id