# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: ECS API
  description: ECS mobiel app API
  version: "1.0.0"
# the domain of the service
host: localhost:8000
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
resourcePath: /Badges
description: All about openid connect provider
apis: 

- path: /getAllProviders/{userId}
  operations:
    - httpMethod: GET
      summary: Get Providers by user
      notes: Fetch all providers by user
      nickname: getAllProviders
      consume:
        - application/json
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token

        - name: userId
          dataType: string
          paramType: path
          description: unique id of user

- path: /updateProvider
  operations:
    - httpMethod: PUT
      summary: update provider
      notes: Returns a updated provider
      nickname: updateProvider
      consumes:
        - application/json
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token
        - name: name
          dataType: string
          paramType: formData
          required: true
          description: organization name
        - name: discoveryUrl
          dataType: string
          paramType: formData
          required: true
          description: Discovery Url
        - name: address
          dataType: string
          paramType: formData
          required: true
          description: organization address
        - name: organizationId
          dataType: string
          paramType: formData
          required: true
          description: unique organization id

- path: /approveProvider
  operations:
    - httpMethod: POST
      summary: approve organization
      notes: Returns a organization based on organization id
      nickname: getOrganizationById
      consumes:
        - application/json
      parameters:
      - name: Authorization
        dataType: string
        paramType: header
        required: true
        description: authorization token
      - name: organizationId
        dataType: string
        paramType: formData
        required: true
        description: organization id
      - name: federationId
        dataType: string
        paramType: formData
        required: true
        description: federation id

- path: /removeProvider/{pid}
  operations:
    - httpMethod: DELETE
      summary: remove organization
      notes: Returns a deleted provider
      nickname: getOrganizationById
      consumes:
        - application/json
      parameters:
      - name: Authorization
        dataType: string
        paramType: header
        required: true
        description: authorization token
      - name: pid
        dataType: string
        paramType: path
        required: true
        description: provider unique id