# this is an example of the Uber API
# as a demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: FIDES API
  description: FIDES web app API
  version: "1.0.0"
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /
resourcePath: /Participants
description: All about users Participant
apis:

- path: /getAllParticipants
  operations:
    - httpMethod: GET
      summary: Get all participant
      notes: Fetch all participant
      nickname: getAllParticipants
      consume:
        - application/json

- path: /getParticipantById/{oid}
  operations:
    - httpMethod: GET
      summary: Get participant by id
      notes: Returns a participant based on participant id
      nickname: getParticipantById
      consumes:
        - application/json
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token
        - name: oid
          dataType: string
          paramType: path
          required: true
          description: participant id

- path: /updateParticipant
  operations:
    - httpMethod: PUT
      summary: Update participant
      notes: Returns a updated participant
      nickname: updateParticipant
      consumes:
        - multipart/form-data
      parameters:
      - name: Authorization
        dataType: string
        paramType: header
        required: true
        description: authorization token
      - name: name
        dataType: string
        paramType: formData
        required: true
        description: participant name
      - name: phoneNo
        dataType: string
        paramType: formData
        required: true
        description: participant phone No
      - name: address
        dataType: string
        paramType: formData
        required: true
        description: participant address
      - name: zipcode
        dataType: string
        paramType: formData
        required: true
        description: participant address
      - name: trustMarkFile
        dataType: file
        paramType: formData
        required: true
        description: trustmark file of participant

- path: /approveParticipant
  operations:
    - httpMethod: POST
      summary: Approved participant
      notes: Returns a approved participant
      nickname: approveParticipant
      consumes:
        - application/json
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token
        - name: participantId
          dataType: string
          paramType: formData
          required: true
          description: participant id
        - name: federationId
          dataType: string
          paramType: formData
          required: true
          description: federation id

- path: /removeParticipant/{oid}
  operations:
    - httpMethod: DELETE
      summary: Remove participant
      notes: Returns a removed participant
      nickname: removeParticipant
      consumes:
        - application/json
      parameters:
        - name: Authorization
          dataType: string
          paramType: header
          required: true
          description: authorization token
        - name: oid
          dataType: string
          paramType: path
          required: true
          description: participant id